# Chapter 2: Working with Text Data

- I'm learning how to prepare and clean text for language modeling
- My goal: understand tokenization and build a small vocabulary
- I want to turn raw text into numeric inputs I can train on

Packages used in this notebook:

In [1]:
from importlib.metadata import version

print("torch version:", version("torch"))
print("tiktoken version:", version("tiktoken"))

torch version: 2.10.0
tiktoken version: 0.12.0


## 2.1 Understanding word embeddings

- I'm learning that for LLMs, tokens are represented as vectors in a high-dimensional space
- These vectors encode relationships that the model can learn
- I find it helpful to use 2D sketches to build intuition about this much larger space

## 2.2 Tokenizing text

- Tokenization splits text into units (words, punctuation, or subwords)
- These units become the inputs the model will work with
- I’ll use a public-domain text (The Verdict) as sample data

In [2]:
import os

# Check for local file first (zero-copy policy compliance)
# The file should already exist in the notebook directory
file_path = "the-verdict.txt"

if not os.path.exists(file_path):
    # Fallback: download from public domain source if local file missing
    # Note: This is a public domain text by Edith Wharton
    import requests
    url = (
        "https://raw.githubusercontent.com/rasbt/"
        "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
        "the-verdict.txt"
    )
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    with open(file_path, "wb") as f:
        f.write(response.content)
    print(f"Downloaded {file_path} from external source")
else:
    print(f"Using local file: {file_path}")


Using local file: the-verdict.txt


In [3]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
    
print("Total number of character:", len(raw_text))
print(raw_text[:99])

Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


- Goal: turn the raw text into tokens a model can consume
- I’ll build a simple regex tokenizer first, then scale it to the full text
- Start by splitting on whitespace to see the baseline behavior

In [4]:
import re

text = "Hello, world. This, is a test."
result = re.split(r'(\s)', text)

print(result)

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


- I noticed that whitespace-only splitting misses punctuation boundaries
- My next step: treat commas and periods as their own tokens

In [5]:
result = re.split(r'([,.]|\s)', text)

print(result)

['Hello', ',', '', ' ', 'world', '.', '', ' ', 'This', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


- I noticed the split introduces empty strings
- I'll filter them out to keep only meaningful tokens

In [6]:
# Strip whitespace from each item and then filter out any empty strings.
result = [item for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'This', ',', 'is', 'a', 'test', '.']


- I'm expanding the pattern to cover more punctuation (e.g., ?, !, quotes)
- This should produce cleaner, more realistic token streams for my model

In [7]:
text = "Hello, world. Is this-- a test?"

result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


- The regex looks good enough for a first pass
- Now I'll apply it to the full text I loaded earlier

In [8]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


- Let me count the total number of tokens I produced

In [9]:
print(len(preprocessed))

4690


## 2.3 Converting tokens into IDs

- I'm learning that models need numbers, not strings
- I'll build a vocabulary mapping each unique token to an integer ID
- Starting by listing unique tokens in a consistent order

In [10]:
all_words = sorted(list(set(preprocessed)))
vocab_size = len(all_words)

print(vocab_size)

1130


- I'll create the token → ID dictionary using a simple enumeration

In [11]:
vocab = {token:integer for integer,token in enumerate(all_words)}

- Let me peek at a handful of entries to sanity-check my mapping

In [12]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


- Next, I’ll wrap the logic into a small tokenizer class
- Then I’ll test it on a short sample string

In [13]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
                                
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

- `encode` converts text into token IDs
- `decode` converts token IDs back into text
- These IDs are what we’ll later feed into embeddings for the model

In [14]:
tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


- I'll decode the IDs to verify the round-trip works

In [15]:
tokenizer.decode(ids)

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [16]:
tokenizer.decode(tokenizer.encode(text))

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

## 2.4 Adding special context tokens

- I noticed a problem: when I try to tokenize text with words not in my vocabulary, it breaks
- I need a way to handle unknown words and mark text boundaries
- I'm learning about special tokens that can help with this

My understanding so far:
- `[UNK]` can represent words not in vocabulary (handles unknown words)
- `[EOS]` marks end of text (useful when concatenating multiple texts)
- `[PAD]` is for padding shorter texts to match longer ones in batches
- `[BOS]` marks beginning of sequence (some tokenizers use this)

I'm curious about GPT-2's approach:
- GPT-2 uses `<|endoftext|>` instead of all those tokens - much simpler!
- It's like `[EOS]` but also used for padding (since we mask padded tokens anyway)
- GPT-2 doesn't use `[UNK]` because it uses BPE (byte-pair encoding) which breaks words into subword units
- I'll learn about BPE later, but for now I'll add `<|unk|>` and `<|endoftext|>` to handle these cases

My takeaway: GPT-2's simpler approach makes sense - one token does multiple jobs when you use masking properly.

Let me see what happens when I try to tokenize text with words not in my vocabulary:


In [17]:
tokenizer = SimpleTokenizerV1(vocab)

text = "Hello, do you like tea. Is this-- a test?"

try:
    tokenizer.encode(text)
except KeyError as e:
    print(f"KeyError: The token {e} is not in the vocabulary.")

KeyError: The token 'Hello' is not in the vocabulary.


- I got an error because "Hello" isn't in my vocabulary
- To handle this, I'll add special tokens like `"<|unk|>"` to represent unknown words
- Since I'm extending the vocabulary anyway, I'll also add `"<|endoftext|>"` which GPT-2 uses to mark the end of text (and between concatenated texts when training on multiple articles or books)

In [18]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

In [19]:
len(vocab.items())

1132

In [20]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


- I also need to adjust my tokenizer so it knows when and how to use the new `<|unk|>` token

In [21]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int 
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

Now let me test the modified tokenizer with some text that includes unknown words and multiple sentences:

In [22]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [23]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]

In [24]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

In [25]:
tokenizer = SimpleTokenizerV2(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)
tokenizer.decode(ids)
tokenizer.decode(tokenizer.encode(text))

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

## 2.5 BytePair encoding

- I'm learning that GPT-2 used BytePair encoding (BPE) as its tokenizer
- BPE lets the model break words that aren't in its vocabulary into smaller subword units or even characters, so it can handle out-of-vocabulary words
- For example, if the vocabulary doesn't have "unfamiliarword," it might tokenize it as something like ["unfam", "iliar", "word"] depending on trained BPE merges
- The original BPE tokenizer is here: [OpenAI encoder.py](https://github.com/openai/gpt-2/blob/master/src/encoder.py)
- In this chapter I'm using the BPE tokenizer from OpenAI's [tiktoken](https://github.com/openai/tiktoken) library, which implements the core algorithms in Rust for better performance
- I created a notebook in [./bytepair_encoder](../02_bonus_bytepair-encoder) that compares the two implementations side-by-side (tiktoken was about 5x faster on my sample text)

In [26]:
# pip install tiktoken

In [27]:
import importlib
import tiktoken

print("tiktoken version:", importlib.metadata.version("tiktoken"))

tiktoken version: 0.12.0


In [28]:
tokenizer = tiktoken.get_encoding("gpt2")

In [29]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [30]:
strings = tokenizer.decode(integers)

print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


## 2.6 Data sampling with a sliding window

- I'm learning that we train LLMs to generate one token at a time, so I need to prepare training data where the next token in a sequence is the target to predict:


In [31]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(f"Encoded Text: {enc_text[:100]}")
print(f"Total Tokens: {len(enc_text)}")

Encoded Text: [40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11, 290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536]
Total Tokens: 5145


- For each text chunk, I need inputs and targets
- Since the model predicts the next token, the targets are the inputs shifted by one position to the right

In [32]:
enc_sample = enc_text[50:]
print("Encoded sample:", enc_sample)
dec_sample = tokenizer.decode(enc_sample)
print("Decoded sample:", dec_sample[:100])

Encoded sample: [290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 286, 22353, 13, 843, 340, 373, 407, 691, 262, 9074, 13, 536, 48819, 508, 25722, 276, 13, 11161, 407, 262, 40123, 18113, 544, 9325, 701, 11, 379, 262, 938, 402, 1617, 261, 12917, 905, 11, 5025, 502, 878, 402, 271, 10899, 338, 366, 31640, 12, 67, 20811, 1, 284, 

In [33]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [290, 4920, 2241, 287]
y:      [4920, 2241, 287, 257]


- One by one, the prediction looks like this:

In [34]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [35]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


- I'll tackle next-token prediction in a later chapter after covering the attention mechanism
- For now, I'm implementing a simple data loader that iterates over the input and returns input/target pairs shifted by one

- I'm using PyTorch here (see Appendix A for installation tips if needed)

In [36]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)

# Set random seeds for reproducibility

torch.manual_seed(42)
np.random.seed(42)

PyTorch version: 2.10.0+cpu


- I'm using a sliding window: move the window by +1 each time:

In [37]:
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [38]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

- Let me test the dataloader with batch size 1 and context size 4:

In [39]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [40]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [41]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


- Example with stride equal to context length (here: 4):
- I can also create batched outputs
- I'm using stride = context length here so batches don't overlap; more overlap can lead to overfitting

In [42]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

# Verify shapes are correct
assert inputs.shape == (8, 4), f"Expected shape (8, 4), got {inputs.shape}"
assert targets.shape == (8, 4), f"Expected shape (8, 4), got {targets.shape}"

print("\n✓ Shape verification passed")

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])

✓ Shape verification passed


## 2.7 Creating token embeddings

- I'm learning that token IDs are still just discrete integers - I need to convert them to continuous vectors
- These vectors (embeddings) will be what the LLM actually works with
- I understand that embeddings are trainable - they get updated during model training
- Let me practice with a simple example to build intuition

In [43]:
# Starting with a simple example: 4 token IDs
input_ids = torch.tensor([2, 3, 5, 1])

- I'll pretend I have a vocabulary of only 6 words and want 3-dimensional embeddings
- This is much smaller than reality, but it helps me visualize what's happening

In [44]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

- The embedding layer creates a 6×3 weight matrix (6 vocab words, 3 dimensions each)
- Let me look at what these initial random weights look like:

In [45]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


- I'm curious about how this works internally
- I noticed that embedding layers are essentially efficient lookup operations
- I learned there's a bonus notebook at [../03_bonus_embedding-vs-matmul](../03_bonus_embedding-vs-matmul) that explains how embeddings relate to one-hot encoding + matrix multiplication
- My understanding: embeddings are trainable neural network layers optimized via backpropagation

- Let me test: convert token ID 3 into its 3-dimensional vector:

In [46]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


- I noticed this is exactly the 4th row (index 3) from the embedding weight matrix!
- Now let me embed all four input_ids at once:

In [47]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


- My key insight: an embedding layer is essentially a lookup table
- Each token ID points to its corresponding row in the weight matrix

**I want to explore more:** I'm curious about how embeddings compare to traditional one-hot encoding + linear layers. I'll check out the bonus content at [../03_bonus_embedding-vs-matmul](../03_bonus_embedding-vs-matmul) later.

## 2.8 Encoding word positions

- I'm realizing there's a problem: embeddings convert token IDs to vectors, but they don't capture **where** the token appears in the sequence
- If I have "cat chased mouse" vs "mouse chased cat", the token embeddings are identical - the model loses position information!
- I'm learning about **positional embeddings** - they encode the position of each token
- The model combines token embeddings + positional embeddings to get the final input representation

Let me try this with GPT-2's approach:

In [48]:
# GPT-2's BPE tokenizer has a vocabulary of 50,257 tokens
# I'll use 256-dimensional embeddings (matching GPT-2 small)
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

- I'll test this with a batch from my dataloader
- With batch_size=8 and max_length=4, I expect shape: (8, 4, 256)
- That's: 8 examples, 4 tokens each, 256-dimensional embeddings

In [49]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [50]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [51]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

# uncomment & execute the following line to see how the embeddings look like
# print(token_embeddings)

torch.Size([8, 4, 256])


- Now I need positional embeddings
- GPT-2 uses **absolute position embeddings** - a learnable embedding for each position
- I'll create another embedding layer, one for each position (0, 1, 2, 3 in my case)

In [52]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

# I can peek at the position embedding weights if curious:
# print(pos_embedding_layer.weight)

In [53]:
# Create position embeddings for positions 0, 1, 2, 3
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

# I can inspect the actual embeddings if needed:
# print(pos_embeddings)

torch.Size([4, 256])


- The final step: add token embeddings + positional embeddings
- This gives the LLM both "what is the token" and "where is it located" information
- I'm learning that this is the actual input the LLM will process

In [54]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

# I can inspect the final combined embeddings:
# print(input_embeddings)

torch.Size([8, 4, 256])


**My mental model so far:**

The input processing pipeline I've built:
1. **Raw text** → (tokenization) → **Token IDs** 
2. **Token IDs** → (embedding layer) → **Token embeddings** (what the token is)
3. **Position indices** → (position embedding layer) → **Position embeddings** (where the token is)
4. **Token embeddings + Position embeddings** → **Input embeddings** (ready for LLM)

This is the foundation I'll build on in Chapter 3 when I learn about attention mechanisms.

## My Chapter 2 Takeaways

**What I learned:**
- Tokenization: from simple regex splitting to BPE (byte-pair encoding)
- Why GPT-2 uses BPE: handles unknown words by breaking them into subword units
- Special tokens: `<|endoftext|>` for boundaries, `<|unk|>` for unknown words
- Sliding window approach for creating training data from long text
- Token embeddings: convert discrete IDs to continuous vectors
- Positional embeddings: encode position information
- Final input = token embeddings + positional embeddings

**What I noticed:**
- Stride affects overlap between training examples (more overlap → potential overfitting)
- Embedding layers are essentially efficient lookup tables
- Without positional embeddings, "cat chased mouse" looks identical to "mouse chased cat"

**I still need to practice:**
- Understanding the math behind why stride affects dataset size
- Building intuition for embedding dimensions
- Exploring the relationship between embeddings and one-hot encoding (bonus notebook)

**Next steps:**
- Chapter 3: Understanding attention mechanisms
- Revisit BPE implementation in [../02_bonus_bytepair-encoder](../02_bonus_bytepair-encoder)
- Study embedding vs matrix multiplication in [../03_bonus_embedding-vs-matmul](../03_bonus_embedding-vs-matmul)